include themes/noctalia.conf


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

font_family Iosevka Term
font_size 15
bold_font auto
italic_font auto
remember_window_size no
background_opacity 0.7
dynamic_background_opacity yes
confirm_os_window_close 0
